env: dev
replicaCount: 2

image:
  tag: d9bfb85cb7c792d86206b03a92f0a7b6e22edd82

ingress:
  enabled: true
  auth:
    enabled: false
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: devlunart.loop.onl
      paths:
      - /
  tls:
    - secretName: devlunart-loop-onl
      hosts:
      - devlunart.loop.onl

autoscaling:
  minReplicas: 2
  maxReplicas: 5
